apiVersion: skaffold/v3
kind: Config
metadata:
  name: browserkube

build:
  artifacts:
    - image: browserkube
      sync:
        infer: ["**/*.go"]
      docker:
        dockerfile: backend/Dockerfile
        buildArgs:
          COMPONENT: browserkube
    - image: sidecar
      sync:
        auto: false
      docker:
        dockerfile: backend/Dockerfile
        buildArgs:
          COMPONENT: sidecar
    - image: ui
      context: ./frontend
      sync:
        infer:
          - app/**/*
      docker:
        dockerfile: Dockerfile
    - image: operator
      context: ./operator
      sync:
        infer: ["**/*.go"]
      docker:
        dockerfile: Dockerfile
    - image: extension-installer
      context: ./cmds/extension-installer
      sync:
        auto: false
      docker:
        dockerfile: Dockerfile
    - image: recorder
      context: ./cmds/recorder
      sync:
        auto: false
      docker:
        dockerfile: Dockerfile
    - image: browser-updater
      sync:
        auto: false
      docker:
        dockerfile: backend/Dockerfile
        buildArgs:
          COMPONENT: browser-updater
    - image: session-archiver
      sync:
        auto: false
      docker:
        dockerfile: backend/Dockerfile
        buildArgs:
          COMPONENT: session-archiver
    - image: x-server
      sync:
        auto: false
      context: ./cmds/x-server
      docker:
        dockerfile: Dockerfile
    - image: vnc-server
      sync:
        auto: false
      context: ./cmds/vnc-server
      docker:
        dockerfile: Dockerfile
    - image: clipboard
      sync:
        auto: false
      docker:
        dockerfile: cmds/clipboard/Dockerfile
  tagPolicy:
    inputDigest: {}
  platforms:
    - linux/amd64
#        - linux/arm64
  local:
    useBuildkit: true
manifests:
  helm:
    flags:
      upgrade:
        - -i
    releases:
      - name: browserkube
        chartPath: helm/charts/browserkube
        namespace: browserkube
        setValueTemplates:
          ingress.enabled: "true"
          operator.repository: '{{.IMAGE_REPO_operator}}'
          operator.tag: '{{.IMAGE_TAG_operator}}@{{.IMAGE_DIGEST_operator}}'
          recorder.repository: '{{.IMAGE_REPO_recorder}}'
          recorder.tag: '{{.IMAGE_TAG_recorder}}@{{.IMAGE_DIGEST_recorder}}'
          ui.repository: '{{.IMAGE_REPO_ui}}'
          ui.tag: '{{.IMAGE_TAG_ui}}@{{.IMAGE_DIGEST_ui}}'
          backend.repository: '{{.IMAGE_REPO_browserkube}}'
          backend.tag: '{{.IMAGE_TAG_browserkube}}@{{.IMAGE_DIGEST_browserkube}}'
          extensionInstaller.repository: '{{.IMAGE_REPO_extension_installer}}'
          extensionInstaller.tag: "{{.IMAGE_TAG_extension_installer}}@{{.IMAGE_DIGEST_extension_installer}}"
          sidecar.repository: '{{.IMAGE_REPO_sidecar}}'
          sidecar.tag: "{{.IMAGE_TAG_sidecar}}@{{.IMAGE_DIGEST_sidecar}}"
          browserUpdater.repository: '{{.IMAGE_REPO_browser_updater}}'
          browserUpdater.tag: "{{.IMAGE_TAG_browser_updater}}@{{.IMAGE_DIGEST_browser_updater}}"
          sessionArchiver.repository: '{{.IMAGE_REPO_session_archiver}}'
          sessionArchiver.tag: "{{.IMAGE_TAG_session_archiver}}@{{.IMAGE_DIGEST_session_archiver}}"
          xServer.repository: '{{.IMAGE_REPO_x_server}}'
          xServer.tag: "{{.IMAGE_TAG_x_server}}@{{.IMAGE_DIGEST_x_server}}"
          vncServer.repository: '{{.IMAGE_REPO_vnc_server}}'
          vncServer.tag: "{{.IMAGE_TAG_vnc_server}}@{{.IMAGE_DIGEST_vnc_server}}"
          clipboard.repository: '{{.IMAGE_REPO_clipboard}}'
          clipboard.tag: "{{.IMAGE_TAG_clipboard}}@{{.IMAGE_DIGEST_clipboard}}"
          blob.rustfs.enabled: true

deploy:
  helm:
    hooks:
      before:
        - host:
            command:
              - sh
              - -c
              - '(cd operator && ./bin/kustomize build config/crd) | kubectl apply -f - '
            os:
              - darwin
              - linux
        - host:
            command:
              - powershell
              - -c
              - cd operator ; kustomize build config/crd | kubectl apply -f -
            os:
              - windows
  statusCheckDeadlineSeconds: 600
profiles:
  - name: arm64
    activation:
      - kubeContext: docker-desktop
        command: dev-arm64
    patches:
      - op: replace
        path: /build/platforms/0
        value: linux/arm64
  - name: dev
    activation:
      - kubeContext: docker-desktop
        command: dev
    patches:
      ## Replace dockerfiles with live-reload enabled
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: backend/develop.dockerfile
      - op: replace
        path: /build/artifacts/3/docker/dockerfile
        value: develop.dockerfile
      ## Dev containers aren't distroless so set proper security context
      - op: add
        path: /manifests/helm/releases/0/setValueTemplates/operator.runAsUser
        value: 65532
      - op: add
        path: /manifests/helm/releases/0/setValueTemplates/operator.runAsGroup
        value: 65532
      ## Since the build is being performed within the container on runtime
      ## disable health check and resource consumption limitations
      - op: add
        path: /manifests/helm/releases/0/setValueTemplates/resources.enabled
        value: false
      - op: add
        path: /manifests/helm/releases/0/setValueTemplates/healthcheck.enabled
        value: false

  - name: remote-dev
    patches:
      - op: add
        path: /manifests/helm/releases/0/setValueTemplates/ingress.hosts[0]
        value: '{{.BROWSERKUBE_INGRESS_HOST}}'
      - op: add
        path: /manifests/helm/releases/0/setValueTemplates/tls[0].hosts[0]
        value: '{{.BROWSERKUBE_INGRESS_HOST}}'
      - op: add
        path: /manifests/helm/releases/0/setValueTemplates/ingress.class
        value: nginx
      - op: replace
        path: /manifests/helm/releases/0/setValueTemplates/ingress.enabled
        value: true
      - op: replace
        path: /build/platforms/0
        value: linux/amd64

  - name: github-build
    build:
      tagPolicy:
        envTemplate:
          template: "{{.BUILD_NUMBER}}"
