{{- if .Values.ingress.enabled }}
{{- $fullName := include "browserkube.fullname" . -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- if .Values.ingress.tls }}
    {{- range $key, $value := .Values.ingress.tlsAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end}}

spec:
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end}}
  ingressClassName: {{ .Values.ingress.class }}
  rules:
  {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /(browserkube)/?(.*)
            pathType: ImplementationSpecific
            backend:
                service:
                  name: {{ $fullName }}-backend
                  port:
                    number: 4444
    {{- end -}}
{{ end }}