apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: browserkube
    control-plane: browserkube-controller-manager
  name: browserkube-operator-controller-manager-metrics-service
  namespace: '{{.Release.Namespace | default "browserkube" }}'
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app.kubernetes.io/name: browserkube
    control-plane: browserkube-controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: browserkube
    control-plane: browserkube-controller-manager
  name: browserkube-operator-controller-manager
  namespace: '{{.Release.Namespace | default "browserkube" }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: browserkube
      control-plane: browserkube-controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: browserkube
        control-plane: browserkube-controller-manager
    spec:
      containers:
        - args:
            - --metrics-bind-address=:8443
            - --health-probe-bind-address=:8081
            - --leader-elect
            - "--sidecar-image={{.Values.sidecar.image}}"
            - "--recorder-image={{.Values.recorder.image}}"
            - "--extension-installer-image={{.Values.extensionInstaller.image}}"
            - "--x-server-image={{.Values.xServer.image}}"
            - "--vnc-server-image={{.Values.vncServer.image}}"
            - "--clipboard-image={{.Values.clipboard.image}}"
            - "--browser-user-configmap={{ .Release.Name }}-browsers-usergroup"
            - "--browser-extension-configmap={{ .Release.Name }}-browser-extension-config"
            - "--browser-readinessprobe-configmap={{ .Release.Name }}-browsers-readinessprobe-config"
{{/*          command:*/}}
{{/*            - /manager*/}}
          image: "{{ .Values.operator.image }}"
          name: manager
          {{- if .Values.healthcheck.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          ports: []
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          {{ end }}
          {{- if .Values.resources.enabled }}
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          {{ end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts: []
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: browserkube-operator-controller-manager
      terminationGracePeriodSeconds: 10
      volumes: []
