{{- if .Values.browserUpdater.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "browserkube.fullname" . }}-browser-updater-cronjob
  namespace: '{{.Release.Namespace | default "default" }}'
  labels: {{ include "labels" . | indent 4 }}
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ template "browserkube.serviceAccountName" . }}
          restartPolicy: Never
          containers:
            - name: browser-updater-job
              command:
                - --namespace {{ .Values.browsers.namespace }}
              image: "{{ .Values.browserUpdater.image }}"
              imagePullPolicy: "{{ .Values.pullPolicy | default "Always" }}"
{{ end }}