apiVersion: api.browserkube.io/v1
kind: BrowserSet
metadata:
  namespace: {{ .Values.browsers.namespace }}
  labels:
    app.kubernetes.io/name: browserset
    app.kubernetes.io/instance: browserset-sample
    app.kubernetes.io/part-of: operator
    {{ include "labels" . | indent 4 }}
  name: browserkube-browserset
spec:
  defaultTimezone: "UTC"
  {{- if .Values.browsers.nodeSelector }}
  podSpec:
    nodeSelector:
      {{ toYaml .Values.browsers.nodeSelector }}
  {{- end }}
  webdriver:
    edge:
      defaultVersion: "124.0"
      defaultPath: "/wd/hub"
      versions:
        "124.0":
          image: browsers/edge:124.0
          port: "4444"
          provider: k8s
    firefox:
      defaultVersion: "125.0"
      defaultPath: "/"
      versions:
        "125.0":
          image: quay.io/browser/firefox-mozilla-build:125.0
          port: "4444"
          provider: k8s
    chrome:
      defaultVersion: "145.0"
      defaultPath: "/"
      versions:
        "145.0":
          image: quay.io/browser/google-chrome-stable:145.0
          port: "4444"
          provider: k8s
    chromium:
      defaultVersion: "145.0"
      defaultPath: "/"
      versions:
        "124.0":
          image: quay.io/browser/chromium:124.0.6367.60-1
          port: "4444"
          provider: k8s
  playwright:
    firefox:
      defaultVersion: "playwright-1.54.0"
      defaultPath: "/"
      versions:
        "playwright-1.54.0":
          image: quay.io/browser/playwright-firefox:playwright-1.54.0
          port: "4444"
          provider: k8s
    chrome:
      defaultVersion: "playwright-1.54.0"
      defaultPath: "/"
      versions:
        "playwright-1.54.0":
          image: quay.io/browser/playwright-chrome:playwright-1.54.0
          port: "4444"
          provider: k8s