apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: browserkube
  name: browserkube-operator-controller-manager
  namespace: {{.Release.Namespace | default "browserkube" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: browserkube
  name: browserkube-operator-leader-election-role
  namespace: {{.Release.Namespace | default "browserkube" }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: browserkube-operator-manager-role
  namespace: {{.Release.Namespace | default "browserkube" }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - get
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsers
      - sessionresults
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsers/finalizers
    verbs:
      - update
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsersets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: browserkube
  name: browserkube-operator-browser-admin-role
rules:
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsers
    verbs:
      - '*'
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsers/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: browserkube
  name: browserkube-operator-browser-editor-role
rules:
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsers/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: browserkube
  name: browserkube-operator-browser-viewer-role
rules:
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsers/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: browserkube
  name: browserkube-operator-browserset-admin-role
rules:
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsersets
    verbs:
      - '*'
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsersets/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: browserkube
  name: browserkube-operator-browserset-editor-role
rules:
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsersets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsersets/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: browserkube
  name: browserkube-operator-browserset-viewer-role
rules:
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsersets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - api.browserkube.io
    resources:
      - browsersets/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: browserkube-operator-metrics-auth-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: browserkube-operator-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: browserkube
  name: browserkube-operator-sessionresult-admin-role
rules:
  - apiGroups:
      - api.browserkube.io
    resources:
      - sessionresults
    verbs:
      - '*'
  - apiGroups:
      - api.browserkube.io
    resources:
      - sessionresults/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: browserkube
  name: browserkube-operator-sessionresult-editor-role
rules:
  - apiGroups:
      - api.browserkube.io
    resources:
      - sessionresults
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - api.browserkube.io
    resources:
      - sessionresults/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: browserkube
  name: browserkube-operator-sessionresult-viewer-role
rules:
  - apiGroups:
      - api.browserkube.io
    resources:
      - sessionresults
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - api.browserkube.io
    resources:
      - sessionresults/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: browserkube
  name: browserkube-operator-leader-election-rolebinding
  namespace: {{.Release.Namespace | default "browserkube" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: browserkube-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: browserkube-operator-controller-manager
    namespace: {{.Release.Namespace | default "browserkube" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: browserkube
  name: browserkube-operator-manager-rolebinding
  namespace: browserkube
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: browserkube-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: browserkube-operator-controller-manager
    namespace: {{.Release.Namespace | default "browserkube" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: browserkube-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: browserkube-operator-metrics-auth-role
subjects:
  - kind: ServiceAccount
    name: browserkube-operator-controller-manager
    namespace: {{.Release.Namespace | default "browserkube" }}