apiVersion: v1
kind: Service
metadata:
  name: {{ include "browserkube.fullname" . }}-backend
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    service: {{ $.Values.name }}
spec:
  ports:
    - name: wd
      port: 4444
      protocol: TCP
      targetPort: 4444
  selector:
    component: {{ include "browserkube.fullname" . }}
  type: ClusterIP