// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	url "net/url"

	mock "github.com/stretchr/testify/mock"
	blob "gocloud.dev/blob"
)

// BucketURLOpener is an autogenerated mock type for the BucketURLOpener type
type BucketURLOpener struct {
	mock.Mock
}

// OpenBucketURL provides a mock function with given fields: ctx, u
func (_m *BucketURLOpener) OpenBucketURL(ctx context.Context, u *url.URL) (*blob.Bucket, error) {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for OpenBucketURL")
	}

	var r0 *blob.Bucket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *url.URL) (*blob.Bucket, error)); ok {
		return rf(ctx, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *url.URL) *blob.Bucket); ok {
		r0 = rf(ctx, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*blob.Bucket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *url.URL) error); ok {
		r1 = rf(ctx, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBucketURLOpener creates a new instance of BucketURLOpener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBucketURLOpener(t interface {
	mock.TestingT
	Cleanup(func())
}) *BucketURLOpener {
	mock := &BucketURLOpener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
