apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: actions-runnerset
  namespace: actions-runner-system
spec:
  replicas: 3
  repository: browserkube/browserkube
  serviceName: browserkube-runners
  selector:
    matchLabels:
      app: browserkube-runners
  template:
    metadata:
      labels:
        app: browserkube-runners
    spec:
      containers:
        - name: runner
          env:
            - name: GOMODCACHE
              value: "/home/runner/.cache/go-mod"
          volumeMounts:
            - name: cache
              mountPath: "/home/runner/.cache"
  volumeClaimTemplates:
    - metadata:
        name: cache
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi