apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: browserkube-runnerdeploy
  namespace: actions-runner-system
spec:
  replicas: 3
  template:
    spec:
      repository: browserkube/browserkube