// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	reference "github.com/distribution/reference"
	mock "github.com/stretchr/testify/mock"

	registry "github.com/browserkube/browserkube/cmd/browser-updater/internal/registry"
)

// RegistryClient is an autogenerated mock type for the RegistryClient type
type RegistryClient struct {
	mock.Mock
}

// Tags provides a mock function with given fields: ctx, ref
func (_m *RegistryClient) Tags(ctx context.Context, ref reference.Named) (*registry.RegistryImageListResp, error) {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Tags")
	}

	var r0 *registry.RegistryImageListResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, reference.Named) (*registry.RegistryImageListResp, error)); ok {
		return rf(ctx, ref)
	}
	if rf, ok := ret.Get(0).(func(context.Context, reference.Named) *registry.RegistryImageListResp); ok {
		r0 = rf(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.RegistryImageListResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, reference.Named) error); ok {
		r1 = rf(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRegistryClient creates a new instance of RegistryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegistryClient {
	mock := &RegistryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
