// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import (
	apiv1 "github.com/browserkube/browserkube/operator/api/v1"

	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// BrowsersSetsInterface is an autogenerated mock type for the BrowsersSetsInterface type
type BrowsersSetsInterface struct {
	mock.Mock
}

func (_m *BrowsersSetsInterface) Patch(ctx context.Context, resourceName string, b []byte, opts v1.PatchOptions) error {
	return nil
}

// Get provides a mock function with given fields: ctx, name, options
func (_m *BrowsersSetsInterface) Get(ctx context.Context, name string, options v1.GetOptions) (*apiv1.BrowserSet, error) {
	ret := _m.Called(ctx, name, options)

	var r0 *apiv1.BrowserSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*apiv1.BrowserSet, error)); ok {
		return rf(ctx, name, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *apiv1.BrowserSet); ok {
		r0 = rf(ctx, name, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.BrowserSet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, opts
func (_m *BrowsersSetsInterface) List(ctx context.Context, opts v1.ListOptions) (*apiv1.BrowserSetList, error) {
	ret := _m.Called(ctx, opts)

	var r0 *apiv1.BrowserSetList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (*apiv1.BrowserSetList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *apiv1.BrowserSetList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.BrowserSetList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Watch provides a mock function with given fields: ctx, pts
func (_m *BrowsersSetsInterface) Watch(ctx context.Context, pts v1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, pts)

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, pts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, pts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, pts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBrowsersSetsInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewBrowsersSetsInterface creates a new instance of BrowsersSetsInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBrowsersSetsInterface(t mockConstructorTestingTNewBrowsersSetsInterface) *BrowsersSetsInterface {
	mock := &BrowsersSetsInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
