version: 3

## override default makefile
## with specific test task for operator
includes:
  root:
    taskfile: ./../.taskfiles/go.yaml
    flatten: true
    excludes: ["test"]
tasks:
  ## proxy tasks to skaffolded Makefile
  test:
    cmd: make test
