name: Check Front-End
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

defaults:
  run:
    working-directory: ./frontend/app
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/app/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npx webpack build

      - name: Run ESLint
        run: npx eslint src/

      - name: Run Stylelint
        run: npx stylelint **/*.scss

      - name: Run Jest tests
        run: npx jest
        env:
          CI: true
